# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'multi-thread-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for multi-thread-demo
  pod 'Masonry'
  pod 'SDWebImage'

end
